/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bean.BeansEspecialidades;
import model.Bean.BeansMedico;
import model.dao.MedicoDAO;
import model.dao.PacienteDAO;

/**
 *
 * @author Marlon Paulo
 */
public class FormMedico extends javax.swing.JFrame {

    BeansMedico m = new BeansMedico();
    Connection con = new ConnectionFactory().getConnection();
    int flag = 0;
    
    public FormMedico() {
        initComponents();
        
        
        
        readJTableMedicos();
    }
    
    
    
    
    public void preencherComboboxEspec(){
        MedicoDAO dao = new MedicoDAO();
        
        for(BeansEspecialidades e: dao.readEspecialidades()){
            
            jComboBoxEspecialista.addItem(e);
        }
    }
    
    
    
    public void readJTableMedicos(){
        DefaultTableModel modelo = (DefaultTableModel) jTableMedicos.getModel();
        
        modelo.setNumRows(0);
        
        MedicoDAO mdao = new MedicoDAO();
        
        for(BeansMedico m: mdao.read()){
            
            modelo.addRow(new Object[]{
               m.getCodigo(),
               m.getCRM(),
               m.getNome(),
               m.getEspecialidade()
               
            });
        }
    }
    public void readJTableByNome(String pesquisa){
        DefaultTableModel modelo = (DefaultTableModel) jTableMedicos.getModel();
        
        modelo.setNumRows(0);
        
        MedicoDAO mdao = new MedicoDAO();
        
        for(BeansMedico m: mdao.readByNome(pesquisa)){
            
            modelo.addRow(new Object[]{
               m.getCodigo(),
               m.getCRM(),
               m.getNome(),
               m.getEspecialidade()
               
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCRM = new javax.swing.JFormattedTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxEspecialista = new javax.swing.JComboBox<>();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicos = new javax.swing.JTable();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelFundoCadastroMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastros de Medicos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 70, 40, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("CRM:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 120, 40, 10);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Especialização:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 180, 90, 14);

        jFormattedTextFieldCRM.setEnabled(false);
        jFormattedTextFieldCRM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldCRMMouseClicked(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldCRM);
        jFormattedTextFieldCRM.setBounds(250, 110, 350, 30);

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNomeMouseClicked(evt);
            }
        });
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(250, 60, 350, 30);

        jComboBoxEspecialista.setEnabled(false);
        jComboBoxEspecialista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxEspecialistaMouseClicked(evt);
            }
        });
        jComboBoxEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecialistaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxEspecialista);
        jComboBoxEspecialista.setBounds(250, 170, 350, 30);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(30, 10, 80, 30);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(30, 50, 80, 30);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(30, 90, 80, 30);

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(30, 130, 80, 30);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(30, 170, 80, 30);

        jTableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "CRM", "Nome", "Especialização"
            }
        ));
        jTableMedicos.setCellSelectionEnabled(true);
        jTableMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedicosMouseClicked(evt);
            }
        });
        jTableMedicos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableMedicosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMedicos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(12, 251, 706, 276);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(580, 210, 90, 30);
        jPanel1.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(400, 210, 176, 30);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Codigo:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 20, 50, 14);

        jTextFieldCodigo.setEnabled(false);
        jTextFieldCodigo.setKeymap(null);
        jPanel1.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(250, 10, 350, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Campo Vazio*");
        jLabel7.setVisible(false);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 90, 64, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Campo Vazio*");
        jLabel8.setVisible(false);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 140, 64, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 50, 730, 540);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Medicos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 20, 170, 22);

        jButtonVoltar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-voltar.png"))); // NOI18N
        jButtonVoltar.setToolTipText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(20, 0, 50, 50);

        jLabelFundoCadastroMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        jLabelFundoCadastroMedico.setText("Voltar");
        getContentPane().add(jLabelFundoCadastroMedico);
        jLabelFundoCadastroMedico.setBounds(0, 0, 880, 640);

        setSize(new java.awt.Dimension(897, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecialistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEspecialistaActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       BeansMedico m = new BeansMedico();
       MedicoDAO dao = new MedicoDAO();
       if(jTextFieldNome.getText().isEmpty()){
           jLabel7.setVisible(true);
           jTextFieldNome.requestFocus();
           
           
           
           
       }else if(jFormattedTextFieldCRM.getText().isEmpty()){
           jLabel8.setVisible(true);
           jFormattedTextFieldCRM.requestFocus();
       }else{
           //jLabel7.setVisible(false);
           //jLabel8.setVisible(false);
       
        if(flag == 1){
       m.setNome(jTextFieldNome.getText());
       m.setCRM(Integer.parseInt(jFormattedTextFieldCRM.getText()));
       
       BeansEspecialidades espe = (BeansEspecialidades) jComboBoxEspecialista.getSelectedItem();
       m.setEspecialidade(espe.getEspecilizacao());
       
       dao.create(m);
       
       jTextFieldNome.setText("");
       jFormattedTextFieldCRM.setText("");
       jTextFieldPesquisa.setText("");
        
       jTextFieldNome.setEnabled(false);
       jFormattedTextFieldCRM.setEnabled(false);
       jComboBoxEspecialista.setEnabled(false);
       jButtonSalvar.setEnabled(false);
       jButtonCancelar.setEnabled(false);
       jButtonExcluir.setEnabled(false);
        
        
       readJTableMedicos();
        }else{
            try {
                
            
        m.setNome(jTextFieldNome.getText());
        m.setCRM(Integer.parseInt(jFormattedTextFieldCRM.getText()));
        
        //BeansEspecialidades espe = (BeansEspecialidades) jComboBoxEspecialista.getSelectedItem();
       // m.setEspecialidade(espe.getEspecilizacao());
        m.setEspecialidade(jComboBoxEspecialista.getSelectedItem().toString());
        m.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro antes de editar  "+e);
            }
        dao.editar(m);
        
        jTextFieldNome.setText("");
        jFormattedTextFieldCRM.setText("");
        jTextFieldPesquisa.setText("");
        
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCRM.setEnabled(false);
        jComboBoxEspecialista.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(true);
        
        readJTableMedicos();
        
        }
       }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        jComboBoxEspecialista.removeAllItems();
        preencherComboboxEspec();
        
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCRM.setEnabled(true);
        jComboBoxEspecialista.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCRM.setEnabled(false);
        jComboBoxEspecialista.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        
        jButtonCancelar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldNome.setText("");
        jFormattedTextFieldCRM.setText("");
        jTextFieldCodigo.setText("");
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        preencherComboboxEspec();
        flag = 2;
        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCRM.setEnabled(true);
        jComboBoxEspecialista.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        
       
        
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCRM.setEnabled(false);
        jComboBoxEspecialista.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        
        readJTableByNome(jTextFieldPesquisa.getText());
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTableMedicosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableMedicosKeyReleased
        
    }//GEN-LAST:event_jTableMedicosKeyReleased

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       BeansMedico m = new BeansMedico();
       MedicoDAO dao = new MedicoDAO();
        
       if(jTableMedicos.getSelectedRow() != -1){
       
           m.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
       
        dao.delete(m);
        jTextFieldNome.setText("");
        jFormattedTextFieldCRM.setText("");
        
        jTextFieldNome.setEnabled(false);
        jFormattedTextFieldCRM.setEnabled(false);
        jComboBoxEspecialista.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        
       readJTableMedicos();
        }else{
            JOptionPane.showMessageDialog(null, "clique em algum cadastro");
            
        }
    
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed
        
    private void jTableMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedicosMouseClicked
        jComboBoxEspecialista.removeAllItems();
        if(jTableMedicos.getSelectedRow() != -1){
        
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        
        jTextFieldCodigo.setText(jTableMedicos.getValueAt(jTableMedicos.getSelectedRow(), 0).toString());
        jFormattedTextFieldCRM.setText(jTableMedicos.getValueAt(jTableMedicos.getSelectedRow(), 1).toString());
        jTextFieldNome.setText(jTableMedicos.getValueAt(jTableMedicos.getSelectedRow(), 2).toString());
        
        jComboBoxEspecialista.addItem(jTableMedicos.getValueAt(jTableMedicos.getSelectedRow(), 3));
        
        
        
        }
       /* if(jTableMedicos.getSelectedRow() != -1){
            
        
        String nome_medico=""+jTableMedicos.getValueAt(jTableMedicos.getSelectedRow(), 2);
        
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        
        ResultSet rs = null;
        try {
            stmt = con.prepareStatement("SELECT * FROM medicos WHERE nome = '"+nome_medico+"'");
            
            rs = stmt.executeQuery();
            
            
            jTextFieldCodigo.setText(String.valueOf(rs.getInt("codigo")));
            jTextFieldNome.setText(rs.getString("nome"));
            jComboBoxEspecialista.setSelectedItem(rs.getString("especialidade"));
            jFormattedTextFieldCRM.setText(rs.getString("CRM"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar"+ex  );
        }
        
        ConnectionFactory.closeConnection(con, stmt);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        }*/
    }//GEN-LAST:event_jTableMedicosMouseClicked

    private void jTextFieldNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNomeMouseClicked
       
               jLabel7.setVisible(false);
           
    }//GEN-LAST:event_jTextFieldNomeMouseClicked

    private void jFormattedTextFieldCRMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCRMMouseClicked
        // TODO add your handling code here:
        jLabel8.setVisible(false);
    }//GEN-LAST:event_jFormattedTextFieldCRMMouseClicked

    private void jComboBoxEspecialistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEspecialistaMouseClicked
       jComboBoxEspecialista.removeAllItems();
        preencherComboboxEspec();
       
    }//GEN-LAST:event_jComboBoxEspecialistaMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        dispose();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<Object> jComboBoxEspecialista;
    private javax.swing.JFormattedTextField jFormattedTextFieldCRM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFundoCadastroMedico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicos;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
