/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bean.BeansAgenda;
import model.Bean.BeansAgendamento;
import model.Bean.BeansMedico;
import model.Bean.BeansPaciente;
import model.dao.AgendamentoDAO;

/**
 *
 * @author Marlon Paulo
 */
public class FormAgenda extends javax.swing.JFrame {
String nomeMed;
    
    Connection con = null;
    /**
     * Creates new form FormAgenda
     */
    public FormAgenda() {
        initComponents();
        
        
        
        Calendar data = Calendar.getInstance();
        Date d = data.getTime();
        SimpleDateFormat  dateFormat =new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.format(d);
        
        String dtHoje;
        dtHoje = dateFormat.format(d);
        String status = "aberto";
        
        readJtableAgenda(status);
        
    }
    /*
    public void preencherTabeladeAgenda(){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"codigo","Nome","Turno","Data","Status","Medico"};
        
        
        con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        
        try {
            stmt = con.prepareStatement("select * from agendamento");
            ResultSet rs = stmt.executeQuery();
            do{
                
            dados.add(new Object[]{rs.getInt("agendamento_cod"),rs.getString("paci_nome"),rs.getString("agendamento_turno"),rs.getDate("agendamento_data"),rs.getString("agendamento_status"),rs.getString("nome")});
                    
            }while(rs.next());
        } catch (SQLException ex) {
            
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
    }
    */
    
        
        
    
    public List<BeansAgenda> readAgenda( String status) {

        Connection con = new ConnectionFactory().getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        List<BeansAgenda> listaAgenda = new ArrayList<BeansAgenda>();

        try {
            stmt = con.prepareStatement("SELECT * FROM agendamento inner join pacientes on agendamento_codPac = paci_codigo inner join medicos on agendamento_codmedico = codigo where agendamento_status = ? order by agendamento_turno");
            
            stmt.setString(1, status);
            rs = stmt.executeQuery();

            while (rs.next()) {
                BeansAgenda agenda = new BeansAgenda();

                
                agenda.setCodigo(rs.getInt("codigo"));
                agenda.setData(rs.getDate("agendamento_data"));
                agenda.setMedico(rs.getString("nome"));
                agenda.setNome(rs.getString("paci_nome"));
                agenda.setStatus(rs.getString("agendamento_status"));
                agenda.setTurno(rs.getString("agendamento_turno"));
                agenda.setMotivo(rs.getString("agendamento_motivo"));
                listaAgenda.add(agenda);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao passar a lista de agendamentos"+ex);
        } finally {
            ConnectionFactory.closeConnection(con, stmt, rs);
        }

        return listaAgenda;
    }

    
    public void readJtableAgenda( String status){
        DefaultTableModel modeloAge = (DefaultTableModel) jTableAgenda.getModel();
        
        modeloAge.setNumRows(0);
        
        
        
        for(BeansAgenda bA: readAgenda(status)){
            modeloAge.addRow(new Object[]{
                bA.getCodigo(),
                bA.getNome(),
                bA.getTurno(),
                bA.getData(),
                bA.getStatus(),
                bA.getMotivo(),
                bA.getMedico()  
            });
            //"codigo","Nome","Turno","Data","Status","Medico"
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Turno", "Data", "Status", "Motivo", "Medico"
            }
        ));
        jScrollPane1.setViewportView(jTableAgenda);
        jTableAgenda.getColumnModel().getColumn(0).setPreferredWidth(1);
        jTableAgenda.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableAgenda.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTableAgenda.getColumnModel().getColumn(3).setPreferredWidth(15);
        jTableAgenda.getColumnModel().getColumn(4).setPreferredWidth(10);
        jTableAgenda.getColumnModel().getColumn(5).setPreferredWidth(100);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agenda");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-voltar.png"))); // NOI18N
        jButton1.setToolTipText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(436, 436, 436)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1210, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormAgendamento tela = new FormAgendamento();
        dispose();
        tela.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAgenda;
    // End of variables declaration//GEN-END:variables
}
